"""
Plan Writer Module

Writes Plan.md files to the vault following the data-model.md format.
Handles YAML frontmatter generation and markdown formatting.

Task T055: Create Plan.md file writer
"""

import json
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from core.vault_interface import VaultInterface
from core.logger import Logger


class PlanWriter:
    """
    Writes structured Plan.md files to the vault plans folder.
    Follows the Plan entity format from data-model.md.
    """

    def __init__(self, vault_interface: VaultInterface, logger: Logger):
        self.vault = vault_interface
        self.logger = logger

    def create_plan(
        self,
        title: str,
        context: str,
        analysis: str,
        actions: List[Dict[str, Any]],
        source_events: List[str],
        expected_outcome: str = "",
        risk_level: str = "medium",
    ) -> Dict[str, Any]:
        """
        Create a Plan.md file in the vault plans folder.

        Args:
            title: Plan title
            context: Event context summary
            analysis: Claude's analysis
            actions: List of recommended action dicts
            source_events: List of source event file paths
            expected_outcome: Expected outcome description
            risk_level: Overall risk level (low/medium/high)

        Returns:
            Dict with plan metadata
        """
        plan_id = str(uuid.uuid4())
        now = datetime.utcnow()
        filename = f"PLAN_{now.strftime('%Y-%m-%d_%H%M%S')}_{plan_id[:8]}.md"

        # Build YAML frontmatter
        metadata = {
            "id": plan_id,
            "title": title,
            "created_at": now.isoformat() + "Z",
            "source_events": source_events,
            "status": "draft",
            "risk_level": risk_level,
        }

        # Format actions as markdown
        actions_md = self._format_actions(actions)

        content = f"""# {title}

## Context
{context}

## Analysis
{analysis}

## Recommended Actions
{actions_md}

## Expected Outcome
{expected_outcome}

---
_Generated by AI Employee reasoning loop at {now.strftime('%Y-%m-%d %H:%M UTC')}_
"""

        # Write to vault
        file_path = self.vault.write_event_file(
            filename=filename,
            metadata=metadata,
            content=content,
            destination_folder="plans",
        )

        self.logger.log_system_event(
            event_type="plan_written",
            component="plan_writer",
            message=f"Plan.md created: {title}",
            details={
                "plan_id": plan_id,
                "file_path": str(file_path),
                "actions_count": len(actions),
                "risk_level": risk_level,
            },
        )

        return {
            "id": plan_id,
            "title": title,
            "file_path": str(file_path),
            "filename": filename,
            "status": "draft",
            "risk_level": risk_level,
            "actions_count": len(actions),
            "created_at": now.isoformat(),
        }

    def _format_actions(self, actions: List[Dict[str, Any]]) -> str:
        """Format actions list as markdown checkboxes."""
        lines = []
        for i, action in enumerate(actions, 1):
            action_type = action.get("action_type", "unknown")
            description = action.get("description", "")
            risk = action.get("risk_level", "medium")
            requires_approval = action.get("requires_approval", False)

            approval_tag = " **[REQUIRES APPROVAL]**" if requires_approval else ""
            risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(risk, "🟡")

            lines.append(
                f"- [ ] **{i}. {action_type}**: {description}{approval_tag} "
                f"({risk_emoji} {risk} risk)"
            )

            # Add proposed content if present
            if action.get("proposed_content"):
                lines.append(f"  ```\n  {action['proposed_content']}\n  ```")

        return "\n".join(lines)

    def update_plan_status(self, plan_path: str, new_status: str) -> bool:
        """
        Update the status of an existing plan.

        Args:
            plan_path: Path to the plan file
            new_status: New status (draft, pending_approval, approved, rejected, executed)

        Returns:
            True if update successful
        """
        try:
            data = self.vault.read_event_file(plan_path)
            metadata = data.get("metadata", {})
            metadata["status"] = new_status

            content = data.get("content", "")
            self.vault.write_event_file(
                filename=plan_path.split("/")[-1] if "/" in str(plan_path) else str(plan_path),
                metadata=metadata,
                content=content,
                destination_folder="plans",
            )

            self.logger.log_system_event(
                event_type="plan_status_updated",
                component="plan_writer",
                message=f"Plan status updated to: {new_status}",
                details={"plan_path": plan_path, "new_status": new_status},
            )
            return True
        except Exception as e:
            self.logger.log_system_event(
                event_type="plan_update_error",
                component="plan_writer",
                message=f"Failed to update plan status: {e}",
                details={"plan_path": plan_path},
            )
            return False

    def get_plans_by_status(self, status: str) -> List[Dict[str, Any]]:
        """Get all plans with a given status."""
        plans = []
        for file_path in self.vault.get_plans():
            try:
                data = self.vault.read_event_file(file_path)
                metadata = data.get("metadata", {})
                if metadata.get("status") == status:
                    plans.append({
                        "file_path": str(file_path),
                        "metadata": metadata,
                    })
            except Exception:
                pass
        return plans
