"""
Plan.md Model

This module represents structured plan files generated by the reasoning skill.
These files include objective, step-by-step actions, required approvals, and expected outcomes.
"""

from datetime import datetime
from typing import Dict, Any, List, Optional


class PlanMd:
    """
    Represents structured plan files generated by the reasoning skill.
    Includes objective, step-by-step actions, required approvals, and expected outcomes.
    """

    def __init__(self, id: str, objective: str, actions: List[Dict[str, Any]],
                 required_approvals: List[str], expected_outcome: str,
                 generated_at: str, status: str = "draft"):
        """
        Initialize a PlanMd instance.

        Args:
            id: Unique identifier for the plan
            objective: Clear objective of the plan
            actions: Array of step-by-step actions
            required_approvals: List of actions requiring approval
            expected_outcome: Expected result of the plan
            generated_at: Timestamp when the plan was created
            status: Status of the plan (draft, approved, executed, rejected)
        """
        self.id = id
        self.objective = objective
        self.actions = actions
        self.required_approvals = required_approvals
        self.expected_outcome = expected_outcome
        self.generated_at = generated_at
        self.status = status

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the PlanMd instance to a dictionary.

        Returns:
            Dictionary representation of the PlanMd
        """
        return {
            "id": self.id,
            "objective": self.objective,
            "actions": self.actions,
            "required_approvals": self.required_approvals,
            "expected_outcome": self.expected_outcome,
            "generated_at": self.generated_at,
            "status": self.status
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'PlanMd':
        """
        Create a PlanMd instance from a dictionary.

        Args:
            data: Dictionary containing PlanMd data

        Returns:
            PlanMd instance
        """
        return cls(
            id=data.get('id', ''),
            objective=data.get('objective', ''),
            actions=data.get('actions', []),
            required_approvals=data.get('required_approvals', []),
            expected_outcome=data.get('expected_outcome', ''),
            generated_at=data.get('generated_at', ''),
            status=data.get('status', 'draft')
        )

    def validate(self) -> bool:
        """
        Validate the PlanMd instance.

        Returns:
            True if the instance is valid, False otherwise
        """
        # Check for required fields
        if not self.id or not self.objective or not self.actions:
            return False

        # Validate objective
        if not isinstance(self.objective, str) or len(self.objective.strip()) == 0:
            return False

        # Validate actions
        if not isinstance(self.actions, list) or len(self.actions) == 0:
            return False

        # Validate required_approvals
        if not isinstance(self.required_approvals, list):
            return False

        # Validate expected_outcome
        if not isinstance(self.expected_outcome, str):
            return False

        # Validate generated_at format (ISO format)
        try:
            datetime.fromisoformat(self.generated_at.replace('Z', '+00:00'))
        except ValueError:
            return False

        # Validate status
        if self.status not in ['draft', 'approved', 'executed', 'rejected']:
            return False

        return True

    def mark_approved(self):
        """
        Mark the plan as approved.
        """
        self.status = "approved"

    def mark_executed(self):
        """
        Mark the plan as executed.
        """
        self.status = "executed"

    def mark_rejected(self):
        """
        Mark the plan as rejected.
        """
        self.status = "rejected"

    def add_action(self, action: Dict[str, Any], requires_approval: bool = False):
        """
        Add an action to the plan.

        Args:
            action: Action to add to the plan
            requires_approval: Whether this action requires approval
        """
        self.actions.append(action)
        if requires_approval:
            # Add the action ID to required approvals if it has one
            action_id = action.get('id')
            if action_id and action_id not in self.required_approvals:
                self.required_approvals.append(action_id)

    def annotate_action_sensitivity(self) -> List[str]:
        """
        Annotate actions as safe or sensitive (requiring approval).

        Returns:
            List of action IDs that are sensitive (require approval)
        """
        sensitive_actions = []

        for action in self.actions:
            # Check if action type is sensitive based on data
            action_type = action.get('type', '')

            # Actions that typically require approval
            sensitive_types = [
                'email_send', 'linkedin_post', 'payment',
                'data_delete', 'external_api_call', 'file_modify_system'
            ]

            if action_type in sensitive_types:
                action_id = action.get('id')
                if action_id and action_id not in self.required_approvals:
                    self.required_approvals.append(action_id)
                    sensitive_actions.append(action_id)

        return sensitive_actions