"""
Plan Model

A Plan.md file generated by the Claude reasoning loop with recommended actions.
Based on data-model.md specification.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class PlanStatus(str, Enum):
    """Status of a plan."""
    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    PARTIALLY_APPROVED = "partially_approved"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"


class RiskLevel(str, Enum):
    """Risk level for plans and actions."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ActionType(str, Enum):
    """Type of action that can be recommended."""
    EMAIL_REPLY = "email_reply"
    EMAIL_SEND = "email_send"
    LINKEDIN_POST = "linkedin_post"
    WHATSAPP_REPLY = "whatsapp_reply"
    ESCALATE = "escalate"
    ARCHIVE = "archive"
    REQUEST_CLARIFICATION = "request_clarification"


@dataclass
class Action:
    """A recommended action within a plan."""
    id: str
    action_type: ActionType
    description: str
    risk_level: RiskLevel
    requires_approval: bool
    approved: bool = False
    executed: bool = False
    proposed_content: Optional[str] = None
    target: Optional[str] = None  # email address, LinkedIn profile, etc.

    @classmethod
    def create(
        cls,
        action_type: ActionType,
        description: str,
        risk_level: RiskLevel = RiskLevel.MEDIUM,
        requires_approval: bool = True,
        proposed_content: Optional[str] = None,
        target: Optional[str] = None,
    ) -> "Action":
        """Create a new action."""
        return cls(
            id=str(uuid.uuid4()),
            action_type=action_type,
            description=description,
            risk_level=risk_level,
            requires_approval=requires_approval,
            proposed_content=proposed_content,
            target=target,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert action to dictionary."""
        return {
            "id": self.id,
            "action_type": self.action_type.value,
            "description": self.description,
            "risk_level": self.risk_level.value,
            "requires_approval": self.requires_approval,
            "approved": self.approved,
            "executed": self.executed,
            "proposed_content": self.proposed_content,
            "target": self.target,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Action":
        """Create action from dictionary."""
        return cls(
            id=data.get("id", str(uuid.uuid4())),
            action_type=ActionType(data.get("action_type", "archive")),
            description=data.get("description", ""),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            requires_approval=data.get("requires_approval", True),
            approved=data.get("approved", False),
            executed=data.get("executed", False),
            proposed_content=data.get("proposed_content"),
            target=data.get("target"),
        )


@dataclass
class Plan:
    """
    A Plan.md file generated by the reasoning loop.

    Plans contain context, analysis, and recommended actions
    based on incoming events from watchers.
    """

    # Required fields
    id: str
    title: str
    created_at: datetime
    source_events: List[str]  # Event IDs
    context: str
    analysis: str
    recommended_actions: List[Action]
    status: PlanStatus
    risk_level: RiskLevel
    file_path: str

    # Optional fields
    expires_at: Optional[datetime] = None
    expected_outcome: Optional[str] = None

    @classmethod
    def create(
        cls,
        title: str,
        source_events: List[str],
        context: str,
        analysis: str,
        recommended_actions: List[Action],
        file_path: str,
        risk_level: RiskLevel = RiskLevel.MEDIUM,
        expected_outcome: Optional[str] = None,
        expires_at: Optional[datetime] = None,
    ) -> "Plan":
        """
        Factory method to create a new Plan.

        Args:
            title: Brief plan title
            source_events: IDs of events that triggered this plan
            context: Background and situation analysis
            analysis: Claude's reasoning about the events
            recommended_actions: List of proposed actions
            file_path: Vault path for the plan file
            risk_level: Overall risk level
            expected_outcome: What will happen if actions are approved
            expires_at: When plan becomes stale

        Returns:
            New Plan instance
        """
        return cls(
            id=str(uuid.uuid4()),
            title=title,
            created_at=datetime.utcnow(),
            source_events=source_events,
            context=context,
            analysis=analysis,
            recommended_actions=recommended_actions,
            status=PlanStatus.DRAFT,
            risk_level=risk_level,
            file_path=file_path,
            expected_outcome=expected_outcome,
            expires_at=expires_at,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert plan to dictionary for serialization."""
        return {
            "id": self.id,
            "title": self.title,
            "created_at": self.created_at.isoformat(),
            "source_events": self.source_events,
            "context": self.context,
            "analysis": self.analysis,
            "recommended_actions": [a.to_dict() for a in self.recommended_actions],
            "status": self.status.value,
            "risk_level": self.risk_level.value,
            "file_path": self.file_path,
            "expected_outcome": self.expected_outcome,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Plan":
        """Create Plan from dictionary."""
        actions = [Action.from_dict(a) for a in data.get("recommended_actions", [])]
        expires_at = None
        if data.get("expires_at"):
            expires_at = datetime.fromisoformat(data["expires_at"])

        return cls(
            id=data.get("id", str(uuid.uuid4())),
            title=data.get("title", "Untitled Plan"),
            created_at=datetime.fromisoformat(data.get("created_at", datetime.utcnow().isoformat())),
            source_events=data.get("source_events", []),
            context=data.get("context", ""),
            analysis=data.get("analysis", ""),
            recommended_actions=actions,
            status=PlanStatus(data.get("status", "draft")),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            file_path=data.get("file_path", ""),
            expected_outcome=data.get("expected_outcome"),
            expires_at=expires_at,
        )

    def to_markdown(self) -> str:
        """Generate Plan.md format for vault storage."""
        risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}
        status_emoji = {
            "draft": "📝",
            "pending_approval": "⏳",
            "partially_approved": "⚡",
            "approved": "✅",
            "rejected": "❌",
            "executed": "🎯",
        }

        actions_md = ""
        for action in self.recommended_actions:
            checkbox = "[x]" if action.approved else "[ ]"
            actions_md += f"""
- {checkbox} **{action.description}**
  - Type: {action.action_type.value}
  - Risk: {risk_emoji.get(action.risk_level.value, '🟡')} {action.risk_level.value.title()}
  - Approval Required: {'Yes' if action.requires_approval else 'No'}
"""
            if action.proposed_content:
                actions_md += f"  - Proposed Content: {action.proposed_content[:100]}...\n"

        markdown = f"""# Plan: {self.title}

**ID**: {self.id}
**Created**: {self.created_at.isoformat()}
**Risk Level**: {risk_emoji.get(self.risk_level.value, '🟡')} {self.risk_level.value.title()}
**Status**: {status_emoji.get(self.status.value, '📝')} {self.status.value.replace('_', ' ').title()}
**Source Events**: {', '.join(self.source_events)}

## Context

{self.context}

## Analysis

{self.analysis}

## Recommended Actions
{actions_md}

## Expected Outcome

{self.expected_outcome or 'Pending analysis completion.'}

---
_Generated by Claude Reasoning Loop at {self.created_at.isoformat()}_
"""
        return markdown

    def get_filename(self) -> str:
        """Generate filename for this plan."""
        timestamp_str = self.created_at.strftime("%Y-%m-%d_%H%M%S")
        short_id = self.id[:8]
        return f"PLAN_{timestamp_str}_{short_id}.md"

    def has_pending_approvals(self) -> bool:
        """Check if plan has actions requiring approval."""
        return any(
            a.requires_approval and not a.approved
            for a in self.recommended_actions
        )

    def get_unapproved_actions(self) -> List[Action]:
        """Get list of actions that need approval."""
        return [
            a for a in self.recommended_actions
            if a.requires_approval and not a.approved
        ]

    def mark_action_approved(self, action_id: str) -> bool:
        """Mark a specific action as approved."""
        for action in self.recommended_actions:
            if action.id == action_id:
                action.approved = True
                self._update_status()
                return True
        return False

    def _update_status(self) -> None:
        """Update plan status based on action states."""
        approved_count = sum(1 for a in self.recommended_actions if a.approved)
        requires_approval = [a for a in self.recommended_actions if a.requires_approval]

        if not requires_approval:
            self.status = PlanStatus.APPROVED
        elif approved_count == 0:
            self.status = PlanStatus.PENDING_APPROVAL
        elif approved_count == len(requires_approval):
            self.status = PlanStatus.APPROVED
        else:
            self.status = PlanStatus.PARTIALLY_APPROVED
