"""
Email Handler — routes approved email requests to email-sender-mcp.

Creates action files in Needs_Action/ for the email MCP server to pick up.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


class EmailHandler:
    """Handles approved email approval requests."""

    ACTION_TYPES = {"email_send", "email", "email_reply", "send_email"}

    def can_handle(self, action_type: str) -> bool:
        return action_type.lower() in self.ACTION_TYPES

    def execute(self, approval_data: Dict[str, Any], vault_path: Path) -> Dict[str, Any]:
        """Create an action file for email-sender-mcp to execute."""
        meta = approval_data.get("metadata", {})
        approval_id = meta.get("id", "unknown")

        needs_dir = vault_path / "Needs_Action"
        needs_dir.mkdir(parents=True, exist_ok=True)

        now = datetime.now(timezone.utc)
        filename = f"SEND_EMAIL_{approval_id[:8]}.md"

        to = meta.get("to", meta.get("recipient", "unknown"))
        subject = meta.get("subject", "No Subject")
        body = approval_data.get("body", meta.get("proposed_content", ""))
        attachments = meta.get("attachments", [])

        attachments_yaml = ""
        if attachments:
            attachments_yaml = "\nattachments:"
            for att in attachments:
                attachments_yaml += f'\n  - "{att}"'

        content = f"""---
type: send_email
action: email_send
approval_id: "{approval_id}"
created: {now.isoformat()}
status: pending
to: "{to}"
subject: "{subject}"{attachments_yaml}
---

# Send Email: {approval_id[:8]}

## To: {to}
## Subject: {subject}

{body}

---
_Generated by Approval Manager at {now.strftime('%Y-%m-%d %H:%M UTC')}_
"""

        action_file = needs_dir / filename
        action_file.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "message": f"Email action created for {to}: {subject}",
            "action_file": str(action_file),
        }
