"""
Invoice Handler — routes approved invoice requests to invoice-generator / email-sender-mcp.

Creates action files in Needs_Action/ for downstream skills to pick up.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


class InvoiceHandler:
    """Handles approved invoice approval requests."""

    ACTION_TYPES = {"send_invoice", "invoice", "invoice_send"}

    def can_handle(self, action_type: str) -> bool:
        return action_type.lower() in self.ACTION_TYPES

    def execute(self, approval_data: Dict[str, Any], vault_path: Path) -> Dict[str, Any]:
        """Create an action file for email-sender-mcp to send the invoice."""
        meta = approval_data.get("metadata", {})
        approval_id = meta.get("id", "unknown")

        needs_dir = vault_path / "Needs_Action"
        needs_dir.mkdir(parents=True, exist_ok=True)

        now = datetime.now(timezone.utc)
        inv_number = meta.get("invoice_number", approval_id[:8])
        filename = f"SEND_INVOICE_{inv_number}.md"

        customer = meta.get("customer", "Unknown Customer")
        customer_email = meta.get("customer_email", meta.get("to", ""))
        total = meta.get("total", "0.00")
        due_date = meta.get("due_date", "")
        pdf_path = meta.get("pdf_path", f"Attachments/{inv_number}.pdf")

        content = f"""---
type: send_invoice
action: invoice_send
approval_id: "{approval_id}"
created: {now.isoformat()}
status: pending
invoice_number: "{inv_number}"
customer: "{customer}"
customer_email: "{customer_email}"
total: {total}
due_date: "{due_date}"
attachments:
  - "{pdf_path}"
---

# Send Invoice {inv_number}: {customer}

## Details

| Field | Value |
|-------|-------|
| Invoice | {inv_number} |
| Customer | {customer} |
| Email | {customer_email} |
| Total | ${total} |
| Due Date | {due_date} |
| PDF | {pdf_path} |

## Instructions

This invoice was approved via HITL workflow.
Email-sender-mcp should send the invoice with PDF attachment.

---
_Generated by Approval Manager at {now.strftime('%Y-%m-%d %H:%M UTC')}_
"""

        action_file = needs_dir / filename
        action_file.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "message": f"Invoice action created: {inv_number} for {customer} (${total})",
            "action_file": str(action_file),
        }
