"""
Payment Handler — routes approved payment requests to payment-handler-mcp.

Creates action files in Needs_Action/ for the payment MCP server to pick up.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


class PaymentHandler:
    """Handles approved payment approval requests."""

    ACTION_TYPES = {"payment", "payment_transfer", "payment_send"}

    def can_handle(self, action_type: str) -> bool:
        return action_type.lower() in self.ACTION_TYPES

    def execute(self, approval_data: Dict[str, Any], vault_path: Path) -> Dict[str, Any]:
        """
        Create an action file for payment-handler-mcp to execute.

        Args:
            approval_data: Parsed approval file metadata + body.
            vault_path: Path to the Obsidian vault.

        Returns:
            {success: bool, message: str, action_file: str|None}
        """
        meta = approval_data.get("metadata", {})
        approval_id = meta.get("id", "unknown")

        needs_dir = vault_path / "Needs_Action"
        needs_dir.mkdir(parents=True, exist_ok=True)

        now = datetime.now(timezone.utc)
        filename = f"EXECUTE_PAYMENT_{approval_id[:8]}.md"

        recipient = meta.get("recipient", meta.get("to", "unknown"))
        amount = meta.get("amount", "0.00")
        currency = meta.get("currency", "USD")
        method = meta.get("method", meta.get("payment_method", "bank_transfer"))

        content = f"""---
type: execute_action
action: payment
approval_id: "{approval_id}"
created: {now.isoformat()}
status: pending
recipient: "{recipient}"
amount: {amount}
currency: "{currency}"
method: "{method}"
---

# Execute Payment: {approval_id[:8]}

## Details

| Field | Value |
|-------|-------|
| Recipient | {recipient} |
| Amount | {currency} {amount} |
| Method | {method} |
| Approval ID | {approval_id} |

## Instructions

This payment was approved via HITL workflow.
Payment-handler-mcp should process this action file.

---
_Generated by Approval Manager at {now.strftime('%Y-%m-%d %H:%M UTC')}_
"""

        action_file = needs_dir / filename
        action_file.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "message": f"Payment action created for {recipient}: {currency} {amount}",
            "action_file": str(action_file),
        }
