"""
Social Handler — routes approved social post requests to social-poster-mcp.

Creates action files in Needs_Action/ for the social MCP server to pick up.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


class SocialHandler:
    """Handles approved social media post approval requests."""

    ACTION_TYPES = {
        "social_post", "linkedin_post", "facebook_post",
        "instagram_post", "twitter_post",
    }

    def can_handle(self, action_type: str) -> bool:
        return action_type.lower() in self.ACTION_TYPES

    def execute(self, approval_data: Dict[str, Any], vault_path: Path) -> Dict[str, Any]:
        """Create an action file for social-poster-mcp to execute."""
        meta = approval_data.get("metadata", {})
        approval_id = meta.get("id", "unknown")

        needs_dir = vault_path / "Needs_Action"
        needs_dir.mkdir(parents=True, exist_ok=True)

        now = datetime.now(timezone.utc)
        platform = meta.get("platform", "linkedin")
        filename = f"POST_SOCIAL_{platform}_{approval_id[:8]}.md"

        content_text = meta.get("proposed_content", approval_data.get("body", ""))
        media = meta.get("media", [])

        media_yaml = ""
        if media:
            media_yaml = "\nmedia:"
            for m in media:
                media_yaml += f'\n  - "{m}"'

        content = f"""---
type: social_post
action: {meta.get('action_type', 'social_post')}
approval_id: "{approval_id}"
created: {now.isoformat()}
status: pending
platform: "{platform}"{media_yaml}
---

# Post to {platform.title()}: {approval_id[:8]}

{content_text}

---
_Generated by Approval Manager at {now.strftime('%Y-%m-%d %H:%M UTC')}_
"""

        action_file = needs_dir / filename
        action_file.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "message": f"Social post action created for {platform}",
            "action_file": str(action_file),
        }
