# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "anthropic>=0.39.0",
#     "pyyaml>=6.0",
#     "python-dotenv>=1.0.0",
# ]
# ///
"""
Bronze Tier Claude Processor — reads action files and creates plans.

Scans Needs_Action/ for unprocessed files, sends them to Claude
for analysis, and saves the response as a plan in Plans/.

This is the simplest possible processor — one file at a time,
no batching, no complex routing. Perfect for learning.

Usage:
    uv run claude_processor.py --vault-path ../obsidian-vault
    uv run claude_processor.py --vault-path ../obsidian-vault --once
    uv run claude_processor.py --vault-path ../obsidian-vault --dry-run
"""

import argparse
import os
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml
from dotenv import load_dotenv

# Load .env from project root
load_dotenv()


def parse_action_file(filepath):
    """
    Read an action file and parse its YAML frontmatter + body.

    Action files look like:
        ---
        type: email
        sender: "someone@example.com"
        subject: "Hello"
        ---
        # Email from someone
        ...body...

    Returns:
        (metadata_dict, body_string)
    """
    content = Path(filepath).read_text(encoding="utf-8")

    if not content.startswith("---"):
        return {}, content

    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}, content

    try:
        metadata = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        metadata = {}

    body = parts[2].strip()
    return metadata, body


def call_claude(prompt, handbook_context=""):
    """
    Send a prompt to Claude and get a response.

    Uses the Anthropic Python SDK. Requires ANTHROPIC_API_KEY in .env.

    Args:
        prompt: The main prompt text.
        handbook_context: Optional company handbook context.

    Returns:
        Claude's response text, or None on failure.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set in .env file")
        print("Get your key from: https://console.anthropic.com/")
        return None

    try:
        from anthropic import Anthropic

        client = Anthropic(api_key=api_key)

        system_prompt = (
            "You are a helpful AI Employee assistant. Your job is to analyze "
            "incoming events (emails, tasks, etc.) and create clear action plans.\n\n"
            "For each event, provide:\n"
            "1. A brief summary\n"
            "2. Priority assessment (high/medium/low)\n"
            "3. Recommended actions (numbered steps)\n"
            "4. A draft reply if applicable\n\n"
            "Be concise and professional."
        )

        if handbook_context:
            system_prompt += f"\n\nCompany context:\n{handbook_context}"

        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            system=system_prompt,
            messages=[{"role": "user", "content": prompt}],
        )

        return response.content[0].text

    except Exception as e:
        print(f"ERROR calling Claude: {e}")
        return None


def create_plan_file(action_filename, metadata, claude_response, vault_path):
    """
    Save Claude's response as a plan file in Plans/.

    Args:
        action_filename: Original action file name (for reference).
        metadata: Metadata from the action file.
        claude_response: Claude's analysis text.
        vault_path: Path to the vault.

    Returns:
        Path to the created plan file.
    """
    plans_dir = Path(vault_path) / "Plans"
    plans_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y%m%d_%H%M%S")
    plan_filename = f"PLAN_{action_filename.replace('.md', '')}_{timestamp}.md"
    filepath = plans_dir / plan_filename

    source_type = metadata.get("type", "unknown")
    subject = metadata.get("subject", "N/A")
    sender = metadata.get("sender", "N/A")

    content = f"""---
type: plan
source_file: {action_filename}
source_type: {source_type}
created: {now.isoformat()}
status: pending_review
---

# Plan: {subject}

**Source:** {action_filename}
**Type:** {source_type}
**From:** {sender}
**Generated:** {now.strftime("%Y-%m-%d %H:%M UTC")}

---

{claude_response}

---

*This plan was generated by your AI Employee. Review and take action!*
"""

    filepath.write_text(content, encoding="utf-8")
    return filepath


def move_to_done(filepath, vault_path):
    """Move a processed action file to Done/."""
    done_dir = Path(vault_path) / "Done"
    done_dir.mkdir(parents=True, exist_ok=True)

    dest = done_dir / Path(filepath).name
    if dest.exists():
        # Avoid collision
        stem = dest.stem
        dest = done_dir / f"{stem}_{int(time.time())}.md"

    shutil.move(str(filepath), str(dest))
    return dest


def log_activity(vault_path, message):
    """Append a log entry."""
    logs_dir = Path(vault_path) / "Logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    log_file = logs_dir / "claude_processor.log"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{timestamp}] {message}\n"

    with open(log_file, "a", encoding="utf-8") as f:
        f.write(line)


def load_handbook(vault_path):
    """Load Company_Handbook.md for context (if it exists)."""
    handbook = Path(vault_path) / "Company_Handbook.md"
    if handbook.exists():
        return handbook.read_text(encoding="utf-8")
    return ""


def process_once(vault_path, dry_run=False):
    """
    Process all action files in Needs_Action/.

    For each file:
    1. Parse the YAML frontmatter and body
    2. Send to Claude for analysis
    3. Save Claude's response as a plan in Plans/
    4. Move the action file to Done/

    Args:
        vault_path: Path to the vault.
        dry_run: If True, print what would happen but don't call Claude.

    Returns:
        Number of files processed.
    """
    needs_action = Path(vault_path) / "Needs_Action"
    if not needs_action.exists():
        return 0

    # Get all .md files
    files = sorted(needs_action.glob("*.md"))
    if not files:
        return 0

    # Load company handbook for context
    handbook = load_handbook(vault_path)

    processed = 0
    for filepath in files:
        filename = filepath.name
        print(f"\n  Processing: {filename}")

        # 1. Parse the file
        metadata, body = parse_action_file(filepath)
        source_type = metadata.get("type", "unknown")
        subject = metadata.get("subject", "N/A")

        print(f"    Type: {source_type}")
        print(f"    Subject: {subject}")

        # 2. Build prompt for Claude
        prompt = (
            f"Please analyze this {source_type} and create an action plan:\n\n"
            f"**From:** {metadata.get('sender', 'unknown')}\n"
            f"**Subject:** {subject}\n"
            f"**Date:** {metadata.get('date_received', 'unknown')}\n\n"
            f"Content:\n{body}\n"
        )

        if dry_run:
            print(f"    [DRY RUN] Would send to Claude ({len(prompt)} chars)")
            print(f"    [DRY RUN] Would create plan in Plans/")
            print(f"    [DRY RUN] Would move to Done/")
            log_activity(vault_path, f"[DRY RUN] Would process: {filename}")
            processed += 1
            continue

        # 3. Call Claude
        print(f"    Sending to Claude...")
        response = call_claude(prompt, handbook)

        if response is None:
            print(f"    FAILED — Claude did not respond")
            log_activity(vault_path, f"FAILED: {filename} — no Claude response")
            continue

        # 4. Save plan
        plan_path = create_plan_file(filename, metadata, response, vault_path)
        print(f"    Plan created: {plan_path.name}")

        # 5. Move to Done
        done_path = move_to_done(filepath, vault_path)
        print(f"    Moved to: Done/{done_path.name}")

        log_activity(vault_path, f"Processed: {filename} → {plan_path.name}")
        processed += 1

    return processed


def run_processor(vault_path, interval=60, once=False, dry_run=False):
    """
    Main processor loop.

    Args:
        vault_path: Path to the Obsidian vault.
        interval: Seconds between checks (default: 60).
        once: If True, process once and exit.
        dry_run: If True, don't actually call Claude.
    """
    print(f"Bronze Claude Processor")
    print(f"  Vault: {vault_path}")
    print(f"  Interval: {interval}s")
    print(f"  Mode: {'single run' if once else 'continuous'}")
    print(f"  Dry Run: {dry_run}")
    print()

    log_activity(vault_path, f"Processor started (dry_run={dry_run})")

    try:
        while True:
            now = datetime.now().strftime("%H:%M:%S")
            print(f"[{now}] Checking Needs_Action/ for files...")

            count = process_once(vault_path, dry_run=dry_run)

            if count > 0:
                print(f"\n  Processed {count} file(s)!")
            else:
                print("  No files to process.")

            if once:
                break

            print(f"  Next check in {interval}s...\n")
            time.sleep(interval)

    except KeyboardInterrupt:
        print("\nProcessor stopped by user.")
        log_activity(vault_path, "Processor stopped (user interrupt)")


def main():
    parser = argparse.ArgumentParser(
        description="Bronze Tier Claude Processor — analyzes action files and creates plans"
    )
    parser.add_argument(
        "--vault-path",
        default="./obsidian-vault",
        help="Path to Obsidian vault (default: ./obsidian-vault)",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=60,
        help="Check interval in seconds (default: 60)",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Process once and exit",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without calling Claude",
    )

    args = parser.parse_args()
    run_processor(args.vault_path, args.interval, args.once, args.dry_run)


if __name__ == "__main__":
    main()
